apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  template:
    metadata:
      name: app
      labels:
        type: front-end
    spec:
      containers:
      - name: app
        image: nginx
        volumeMounts:
        - name: persistent-storage
          mountPath: /usr/share/nginx/html
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: ebs-claim
  replicas: 3
  selector:
    matchLabels:
      type: front-end
